CREATE DATABASE ImdbDb

USE ImdbDb

CREATE TABLE Directors(
	Id INT PRIMARY KEY IDENTITY,
	Fullname NVARCHAR(100) NOT NULL
)

CREATE TABLE Movies(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(120) NOT NULL UNIQUE,
	RealeseDate DATETIME2 DEFAULT GETDATE(),
	Duration INT NOT NULL,
	Description NVARCHAR(500) NOT NULL,
	ImdbPoint FLOAT NOT NULL CHECK(ImdbPoint >= 0),
	DirectorId INT FOREIGN KEY REFERENCES Directors(Id)
)

CREATE TABLE Genres(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE MovieGenres(
	Id INT PRIMARY KEY IDENTITY,
	MovieId INT FOREIGN KEY REFERENCES Movies(Id),
	GenreId INT FOREIGN KEY REFERENCES Genres(Id)
)

CREATE TABLE MovieImages(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(120) NOT NULL UNIQUE,
	MovieId INT FOREIGN KEY REFERENCES Movies(Id) 
)

CREATE TABLE Actors(
	Id INT PRIMARY KEY IDENTITY,
	Fullname NVARCHAR(150) NOT NULL
)

CREATE TABLE MovieActors(
	Id INT PRIMARY KEY IDENTITY,
	MovieId INT FOREIGN KEY REFERENCES Movies(Id),
	ActorId INT FOREIGN KEY REFERENCES Actors(Id)
)

SELECT M.Name 'MovieName', M.ImdbPoint, G.Name 'GenreName',
       D.Fullname 'DirectorFullname', A.Fullname 'ActorFullname'
FROM Movies AS M
JOIN MovieGenres AS MG
ON M.Id = MG.MovieId
JOIN Genres AS G
ON G.Id = MG.GenreId
JOIN Directors AS D
ON M.DirectorId = D.Id
JOIN MovieActors AS MA
ON M.Id = MA.MovieId
JOIN Actors AS A
ON A.Id = MA.ActorId